"""Render an Ollama Modelfile so `ollama run rinn` behaves like the Python assistant."""
from __future__ import annotations

from .config import Settings
from .persona import build_system_prompt


def render_modelfile(settings: Settings | None = None, base_model: str | None = None) -> str:
    """Return Modelfile text for ``settings`` (defaults when omitted)."""
    current = settings or Settings()
    prompt = build_system_prompt(current.extra_instructions)
    if '"""' in prompt:
        raise ValueError("system prompt must not contain triple quotes")

    lines = [
        "# RINN model definition for Ollama.",
        "# Generated by scripts/build_modelfile.py from rinn/persona.py and rinn/config.py.",
        "# Regenerate instead of editing by hand:  python scripts/build_modelfile.py",
        "#",
        "# Build:  ollama create rinn -f Modelfile",
        "# Run:    ollama run rinn",
        f"FROM {base_model or current.model}",
        f"PARAMETER temperature {current.temperature}",
        f"PARAMETER top_p {current.top_p}",
        f"PARAMETER num_ctx {current.num_ctx}",
        f"PARAMETER repeat_penalty {current.repeat_penalty}",
    ]
    if current.num_predict != -1:
        lines.append(f"PARAMETER num_predict {current.num_predict}")
    if current.seed is not None:
        lines.append(f"PARAMETER seed {current.seed}")
    lines += ["", 'SYSTEM """', prompt, '"""', ""]
    return "\n".join(lines)
